In [1]:
# Titanic Dataset Features:
# survived: Whether the passenger survived (0 = No, 1 = Yes).
# pclass: Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd).
# sex: Gender of the passenger.
# age: Age of the passenger in years. Some values are missing.
# sibsp: Number of siblings/spouses aboard the Titanic.
# parch: Number of parents/children aboard the Titanic.
# fare: Passenger fare.
# embarked: Port of embarkation (C = Cherbourg; Q = Queenstown; S = Southampton).
# class: Duplicate of 'pclass' (used for plotting by Seaborn).
# who: Describes whether the passenger is a man, woman, or child.
# adult_male: Indicates whether the passenger is an adult male (True/False).
# deck: The deck the passenger was on (missing for many passengers).
# embark_town: The name of the town where the passenger boarded.
# alive: Indicator of whether the passenger survived (Yes/No, derived from 'survived').
# alone: Indicates whether the passenger was traveling alone (True/False).

In [108]:
import pandas as pd
import sklearn
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [85]:
# load the dataset

titanic_data ="data/titanic.csv"
titanic_df = pd.read_csv(titanic_data)
titanic_df.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [65]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [66]:
titanic_df.select_dtypes(include = 'object').columns
# titanic_df.select_dtypes(include = 'object').columns.tolist()
# titanic_df.select_dtypes(include = ['object', 'int64'])
# titanic_df.select_dtypes(include = ['object', 'int64'])[:5]
# titanic_df.select_dtypes(exclude = ['object'])[:5]

/var/folders/19/_m__1vl122lfw6k451rx98840000gp/T/ipykernel_89611/2323604067.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  titanic_df.select_dtypes(include = 'object').columns

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='str')

In [97]:
titanic_df['Embarked'].value_counts()
# titanic_df['Embarked'].isna().sum()
# titanic_df['Age'].isna().sum()
# titanic_df['Cabin'].isna().sum()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [98]:
#Pre Processing

titanic_df.Embarked = titanic_df.Embarked.fillna(titanic_df['Embarked'].mode()[0])

#mean : average value of the data
#median : middle value of the data
#mode : most frequently occurring value in the data

In [86]:
median_age = titanic_df.Age.median()
median_fare = titanic_df.Fare.median()
print(median_age)
print(median_fare)

titanic_df['Age']=titanic_df['Age'].fillna(median_age)
titanic_df.Fare.fillna(median_fare, inplace = True)

28.0
14.4542

/var/folders/19/_m__1vl122lfw6k451rx98840000gp/T/ipykernel_89611/3616017433.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  titanic_df.Fare.fillna(median_fare, inplace = True)

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [88]:
titanic_df.drop('Cabin', axis = 1, inplace = True)

In [90]:
titanic_df['FamilySize'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df['GenderClass'] = titanic_df.apply(lambda x: 'child' if x['Age'] < 15 else x['Sex'],axis = 1)

In [91]:
# titanic_df[titanicdf.Age<15].head(2)
titanic_df['GenderClass'].value_counts()
# titanic_df['Embarked'].value_counts()

GenderClass
male      538
female    275
child      78
Name: count, dtype: int64

In [92]:
# titanic_df["Pclass"].unique()
titanic_df.Pclass.unique()
#titanic_df['Embarked'].value_counts()

array([3, 1, 2])

In [93]:
titanic_df.groupby("Pclass").count()

        PassengerId  Survived  Name  ...  Embarked  FamilySize  GenderClass
Pclass                               ...
1               216       216   216  ...       214         216          216
2               184       184   184  ...       184         184          184
3               491       491   491  ...       491         491          491

[3 rows x 12 columns]

In [75]:
#dict(titanic_df.groupby("Pclass")['PassengerId'].count())

In [76]:
#titanic_df.groupby('Embarked').count()

In [94]:
titanic_df.groupby('Survived').count()
#titanic_df.groupby('Survived')['PassengerId'].count()

          PassengerId  Pclass  Name  ...  Embarked  FamilySize  GenderClass
Survived                             ...
0                 549     549   549  ...       549         549          549
1                 342     342   342  ...       340         342          342

[2 rows x 12 columns]

In [95]:
#frequency of unique values
titanic_df['Survived'].value_counts()
#titanic_df['Embarked'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [99]:
#checking for missing values
print("Missing values in each column:")
print(titanic_df.isnull().sum())

Missing values in each column:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
FamilySize     0
GenderClass    0
dtype: int64

In [100]:
titanic_df.head(3)

   PassengerId  Survived  Pclass  ... Embarked FamilySize  GenderClass
0            1         0       3  ...        S          2         male
1            2         1       1  ...        C          2       female
2            3         1       3  ...        S          1       female

[3 rows x 13 columns]

In [102]:
titanic_df=pd.get_dummies(titanic_df, columns=['GenderClass', 'Embarked'], drop_first=True)
titanic_df.head(3)

KeyError: "None of [Index(['GenderClass', 'Embarked'], dtype='str')] are in the [columns]"

In [103]:
titanic_df1 = titanic_df.drop(['Name','Sex','Ticket'],axis=1)

In [104]:
X = titanic_df1.drop('Survived', axis=1)
y = titanic_df1['Survived']

In [105]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [109]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=42)

In [110]:
model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [111]:
predictions = model.predict(X_test)

In [112]:
confusion_matrix(y_test, model.predict(X_test))

array([[90, 15],
       [23, 51]])

In [113]:
report = classification_report(y_test, predictions)
print(report)

              precision    recall  f1-score   support

           0       0.80      0.86      0.83       105
           1       0.77      0.69      0.73        74

    accuracy                           0.79       179
   macro avg       0.78      0.77      0.78       179
weighted avg       0.79      0.79      0.79       179

classification_report gives a class-wise performance summary
It reports 4 key metrics per class:

Precision
Recall
F1-score
Support
Precision (per class) : Of all passengers predicted as a given class, how many were correct?

For class1 (Survived) : precision = 0.76

Out of all passengers predicted as survived, 76% actually survived
Recall (per class) : Of all actual passengers in a class, how many did the model correctly identify? For class1 (Survived) : recall = 0.64

Out of all passengers who actually survived, the model identified 64%
36% of survivors were missed (false negatives)
F1-score : Harmonic mean of Precision and Recall F1 = 2 × (Precision × Recall) / (Precision + Recall)

For class1 (Survived) : f1-score = 0.69

Balanced measure when both precision and recall matter
Useful when classes are imbalanced (Titanic is slightly imbalanced)
Support : support = 74

There are 74 actual survivors in the test set
Metrics for this class are calculated using these 74 rows
Accuracy (overall) : accuracy = 0.79

Model correctly predicted 79% of all passengers Accuracy alone is misleading if:
Dataset is imbalanced
One class dominates (non‑survivors in Titanic)
Macro vs Weighted Average Macro Avg = simple average across classes

Treats survivors and non‑survivors equally
Ignores class imbalance
Weighted Avg = weighted by support

Accounts for class imbalance

In [115]:
model.coef_
# Positive coefficient → increases survival probability
# Negative coefficient → decreases survival probability
# Example interpretation:
# Sex_female = +2.1 → Being female strongly increases survival chance
# Pclass_3 = -1.3 → 3rd class reduces survival probability

array([[ 4.55101029e-04, -7.29385102e-01, -1.02827495e-02,
        -9.42876424e-01, -7.77732177e-01,  5.01537814e-03,
         5.60638492e-01,  5.75966074e-01, -2.49678202e+00,
        -2.39517367e-01, -3.23973397e-01]])

In [116]:
X_test.head()

     PassengerId  Pclass   Age  ...  GenderClass_male  Embarked_Q  Embarked_S
709          710       3  28.0  ...              True       False       False
439          440       2  31.0  ...              True       False        True
840          841       3  20.0  ...              True       False        True
720          721       2   6.0  ...             False       False        True
39            40       3  14.0  ...             False       False       False

[5 rows x 11 columns]

In [117]:
y_test.head()

709    1
439    0
840    0
720    1
39     1
Name: Survived, dtype: int64